<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href='/assets/css/main.css' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1>Getting Started</h1>

        <p>So you want to seat some people and don't know where to start?</p>
        <p>Then you have come to the right place!</p>

        <p>Regardless of what kind of event <b>Seat Me</b> makes it easy to make the perfect setting arrangment</p>
        <p>Got an aunt that don't like sitting next to the cool friend of your? No worries we got that covered as well</p>
    </body>
</html>
